apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
    app: votingapp
spec:
  selector:
    name: db
  type: ClusterIP
  ports:
    - name: db
      port: 5432
      targetPort: 5432

