apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    app: votingapp
spec:
      containers:
      - image: redis
        name: redis
        resources:
          limits:
            cpu: "50m"
          requests:
            cpu: "50m"
        ports:
        - name: redis
          containerPort: 6379
          hostPort: 6379


