apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    name: worker
    app: votingapp
spec:
  selector:
    name: worker
  type: ClusterIP
  ports:
    - name: worker
      port: 27016
      targetPort: 27016

